= UniversalJSON

* This is a check plugin for checkmk with a ruleset.
* It aims to be a "better" local check.

== Advantages

* agent data is structured because it uses JSON.
* The agent can decide if the state is OK, WARNING, CRITICAL, or UNKNOWN just like with local checks ...
* But you can configure service rules to override the state 🍾 based on if threshold value are exceeded.
* In other words: If you have metrics, you can configure thresholds on the checkmk server.
* Unlike local checks it supports counters 🍻 !!!
* You can emit your own details and summary.

== How does this work?

=== One OK service with details summary.

.simple example
----
<<<universaljson:sep(0)>>>
{"services":{"service0":{"summary":"summary for service0","details":"details for service0, expected to be OK","state":0}}}
----

As common with checkmk, the JSON is expected to be on one line.

.to make it better readable for humans:
----
<<<universaljson:sep(0)>>>
{
  "services": {
    "service0": {
      "summary": "summary for service0",
      "details": "details for service0, expected to be OK",
      "state": 0
    }
  }
}
----

As common with checkmk, the JSON is expected to be on one line.
Here it's just pretty printed to make it better to understand.


.more complex JSON example
----
<<<universaljson:sep(0)>>>
{"services":{"service0":{"summary":"summary for service0","details":"details for service0, expected to be OK","state":0},"service1":{"summary":"summary for service1","details":"details for service1, expected to be WARN","state":1},"service2":{"summary":"summary for service2","details":"details for service2, expected to be CRIT","state":2},"service3":{"summary":"summary for service3","details":"details for service3, expected to be UNK","state":3},"service4":{"state":0,"summary":"summary for service4","details":"details for service4","metrics":{"temp":46,"humidity":70}},"service5":{"summary":"summary for service5","details":"details for service5, it's a counter","metrics":{"mycounter":"1754224044c"}}}}
----

.same as multiline for better readebility 
----
<<<universaljson:sep(0)>>>
{
  "services": {
    "service0": {
      "summary": "summary for service0",
      "details": "details for service0, expected to be OK",
      "state": 0 
    },
    "service1": {
      "summary": "summary for service1",
      "details": "details for service1, expected to be WARN",
      "state": 1 
    },
    "service2": {
      "summary": "summary for service2",
      "details": "details for service2, expected to be CRIT",
      "state": 2
    },
    "service3": {
      "summary": "summary for service3",
      "details": "details for service3, expected to be UNK",
      "state": 3 
    },
    "service4": {
      "state": 0, 
      "summary": "summary for service4",
      "details": "details for service4",
      "metrics": {
        "temp": 46.0,
        "humidity": 70.0 
      }
    },
    "service5": {
      "summary": "summary for service5",
      "details": "details for service5, it's a counter",
      "metrics": {
        "mycounter": "1754143835c"
      }
    }
  }
}
----


* service4 genereates two float metrics temp and humidity
* service5 generates a metric which is actually a counter because it's a string (using "quotes") and has a suffix of "c", like it was common in nagios compatible checks.




